repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run tests
        entry: ./tests/run.sh
        language: system
        pass_filenames: false
        always_run: true
        verbose: true