repos:
  - repo: local
    hooks:
      - id: run-tox
        name: Run tox
        entry: ./tests/run.sh
        language: system
        pass_filenames: false
        always_run: true
        verbose: true