[tool.poetry]
name = "ormwtf"
version = "0.1.0"
description = "Python ORM wrappers"
authors = ["Lev Litvinov <misery7100@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">3.10,<3.12"
redis = "^5.0.8"
pydantic = "^2.8.2"
pymongo = "^4.8.0"
motor = "^3.5.1"
pydantic-settings = "^2.4.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"

[tool.poetry-dynamic-versioning.files."ormwtf/__version__.py"]
persistent-substitution = true
initial-content = """
  # These version placeholders will be replaced later during substitution.
  __version__ = "0.0.0"
  __version_tuple__ = (0, 0, 0)
"""

[build-system]
requires = ["poetry-core", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
